### ISSUE TITLE
APP_DEBUG=0 and custom monolog handler will not boot kernel due to exception: non-existent parameter "container.build_id"

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1822]
**Description** 
As you access various services inside compiler passes, if a monolog handler has a reference to the event dispatcher and the handler is assigned to the `app` channel.

With APP_DEBUG=0 this fails with 

```
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "container.build_id".             
```

due to accessing MigrationCollector in `\Shopware\Core\Framework\Migration\MigrationCompilerPass::process`. If not that one there are probably others.

Files:

services/services.yaml:
```yaml
services:
    _defaults:
        autoconfigure: false
        autowire: false
        public: false

    Shopware\Production\FoobarLogHandler:
        calls:
            - setEventDispatcher: [ '@event_dispatcher' ]
```

Add the import to services.xml:
```

        <import resource="services/services.yaml" />
```

Class:
```php
<?php declare(strict_types=1);

namespace Shopware\Production;

use Monolog\Handler\AbstractHandler;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class FoobarLogHandler extends AbstractHandler
{
    private EventDispatcherInterface $eventDispatcher;

    public function setEventDispatcher(EventDispatcherInterface $eventDispatcher): void
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function handle(array $record): void
    {
    }
}
```

monolog.yaml

```yaml
monolog:
    handlers:
        massive_logger:
            type: 'service'
            id: 'Shopware\Production\FoobarLogHandler'
            level: 'debug'
            nested: false
            channels: [ 'app' ]
```

This configuration will fail with the above mentioned error.

if the calls from the `services.yaml` are removed but everything else is kept it will work but it should work also if event dispatcher is injected.

Now execute:

```
APP_URL=http://localhost APP_DEBUG=0 APP_ENV=prod bin/console cache:clear -vv
```

to see the error.

It might also be necessary for the logger to be assigned to the `app` channel for this issue to occur.

**Possible Solution**  
Do not access services inside compiler passes.
