### ISSUE TITLE
Composer v2 allow-plugins requirement. The helper "question" is not defined.

### ISSUE THREAD

**Issue by augsteyer** [shopware/platform#2252]
### PHP Version

7.4.27

### Shopware Version

6.4.6.0

### Expected behaviour

Expected `bin/console system:install --drop-database --basic-setup --force` command to complete on Shopware docker image.

### Actual behaviour

Error appears. Seems like when it's running `plugin:refresh` stage of the `system:install` CLI command.

```text
Shopware Plugin Service
=======================

<warning>bamarni/composer-bin-plugin contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins</warning>

The helper "question" is not defined.
```

### TLDR; Fix

`composer install --non-interactive` command creates the issue.
Composer 2 new requires that plugins that have executable code need to be explicitly allowed in `composer.json`.
Assumingely acceptable fix:
```json
        "allow-plugins": {
            "bamarni/composer-bin-plugin": true,
            "phpstan/extension-installer": true
        }
```

### Reproduce

Steps 1-2 are tentative, maybe some adjustments may need to be done for your environment.

1. Create `docker-compose.yml`
```yaml
version: "3"
services:
  sw-dev:
    image: shopware/development:7.4-composer-2
    ports:
      - "80:80"
    networks:
      - sw-dev-web
  sw-dev-mysql:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - sw-dev-web
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root

networks:
  sw-dev-web:
    external: false
```
2. `docker-compose up -d`
3. `docker ps` - this is for next command
4. `docker exec -it [CONTAINER_ID] /bin/bash`
5. `git clone https://github.com/shopware/platform.git . --branch 6.4.6.0` - I tested on 6.4.7.0 previously as well. Same issue.
6. `composer install -n` - yes, non-interactive mode. If interactive, the issue will be apparent, it asks to allow running of plugins. But not interactive mode (e.g. for CI) will silently fail to run the code which will produce the problem mentioned here.
