### ISSUE TITLE
Redis number ranges has a dependency on a non-existent service "shopware.cart.redis".

### ISSUE THREAD

**Issue by lutek** [shopware/platform#2580]
### PHP Version

7.4.29

### Shopware Version

6.4.12.0

### Expected behaviour

Number Ranges handled by Redis

### Actual behaviour

error

```
The service "Shopware\Core\System\NumberRange\ValueGenerator\Pattern\IncrementStorage\IncrementRedisStorage" has a dependency on a non-existent service "shopware.cart.redis".
```

### How to reproduce

Enable in config:

```
shopware:
    number_range:
        increment_storage: "Redis"
        redis_url: '%env(string:REDIS_URL)%/1'
```
