### ISSUE TITLE
shopware.logger.exclude_exception - exceptions still being logged

### ISSUE THREAD

**Issue by Turbulentarius** [shopware/platform#2949]
### PHP Version

8.1.2

### Shopware Version

6.4.18.1

### Expected behaviour

The exceptions you list for exclusion in the `shopware.yaml` should not be reported in the log. E.g.

```
shopware:
    logger:
        exclude_exception:
               - Shopware\Storefront\Framework\Captcha\Exception\CaptchaInvalidException
               - Shopware\Core\Content\Media\Exception\DuplicatedMediaFileNameException
               - League\OAuth2\Server\Exception\OAuthServerException
```

### Actual behaviour

The log files are spammed with exceptions for more or less relevant things. E.g:

```
Uncaught PHP Exception League\OAuth2\Server\Exception\OAuthServerException: "The resource owner or authorization server denied the request."
```

### How to reproduce

Add the following to `shopware.yaml`:

```
shopware:
    logger:
        exclude_exception:
               - Shopware\Storefront\Framework\Captcha\Exception\CaptchaInvalidException
               - Shopware\Core\Content\Media\Exception\DuplicatedMediaFileNameException
               - League\OAuth2\Server\Exception\OAuthServerException
```
Remember to clear cache, observe, the exceptions are still reported in the prod log `var/www/shopware/var/log/`.

**Comment by Turbulentarius** [comment]
I just tested if running `git pull` before `composer update` would fix it, when doing an update from **6.4.18.0** to **6.4.18.1**, but it seems not. E.g. "`Already up to date.`".

**Comment by Tim-VL** [comment]
Any updates on this matter? My log has about 84 pages of this error.... (left browser open after office hours)
using 6.4.19.0

**Comment by Turbulentarius** [comment]
Yes, but I don't even know if this is an actual bug, or if it is just our setup that has inaccurate configuration. It is nice to be able to filter certain events though, because they may be expected to happen and therefore irrelevant.

But, I have looked into how to configure Monolog properly, and it seems some events are logged as critical errors, when they should perhaps only have been `notice` or `warning` level, which in my mind is a bit excessive. The log spam with `OAuthServerException` can be avoided by changing the logging level of monolog to `alert`, but this requires a `fingers_crossed` handler, and may cause you to miss important error messages. You can do it like this, in `config/packages/prod/monolog.yaml`:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: alert
            handler: nested
        nested:
            type: rotating_file
            level: alert
        business_event_handler_buffer:
            level: alert
            type: rotating_file
            max_files: 2
```
  **Note.** You can have seperate Monolog configurations for `prod` and `dev` simply by keeping them in separate directories. It also avoids errors when switching from `dev` to `prod` when something is not recognised because it is mode-specific. Finally, remember to do `cache:clear` after changing monolog config.

  
This was not documented anywhere, and I had to dig down in various github examples to deduce that this was possible.

My guess is, surely it is not a critical error that a session expires? In fact, I would argue such a situation is to be expected and should not even be logged unless it is triggered by some sort of error. Ok, Maybe it is an error, because you also got the `cannot read properties of undefined` notifications on the login page, and that really should not be shown to users. Idk.
