### ISSUE TITLE
Shopware watch-administration.sh not working after remove shopware/storefront package

### ISSUE THREAD

**Issue by maximilian-schwarz** [shopware/platform#3248]
### PHP Version

8.2

### Shopware Version

6.5.3.3

### Expected behaviour

I expect that I can now call the administration and after each change the administration area is recompiled.

### Actual behaviour

I am running Shopware 6 as headless. Accordingly, I have removed the package "shopware/storefront" from composer.json. And execute "composer update" everything is fine.

But if i run the following command the administration is not working:
```
bin/watch-administration.sh
```

Unfortunately the following error appears then:
```
GET http://shopware.ddev.site:9997/sw-plugin-dev.json 404 (Not Found))
```

### How to reproduce

Install a fresh shopware 6 with the flex template:
```
composer create-project shopware/production
```

After the installation run the following command:
```
composer remove shopware/storefront && composer remove shopware/elasticsearch
```

Call the administration everything is fine.
```
https://shopware.ddev.site/admin
```

If you call the command "bin/watch-administration.sh" the administration is not callable after the login.
```
http://shopware.ddev.site:9997
```

Unfortunately the following error appears then:
```
GET http://shopware.ddev.site:9997/sw-plugin-dev.json 404 (Not Found))
```

-----

If i execute the following command and add the package "shopware/storefront":
```
composer require shopware/storefront
```

Everything is working like expected.

**Comment by zaifastafa** [comment]
@maximilian-schwarz hi can you tell me how your docker-compose.watcher.yaml looks like? i dont have bin/watch:administration.sh instead i use ddev composer watch:admin command and I cannot reach the shop at 9997 it says bad gateway

**Comment by maximilian-schwarz** [comment]
> @maximilian-schwarz hi can you tell me how your docker-compose.watcher.yaml looks like? i dont have bin/watch:administration.sh instead i use ddev composer watch:admin command and I cannot reach the shop at 9997 it says bad gateway

@zaifastafa

1. Step: ddev poweroff

2. Step: Create a file .ddev/docker-compose.shopware.yml
```
version: "3.6"

services:
  web:
    expose:
      # Storefront Hot Proxy Ports
      - 9997
      - 9998
      - 9999
    environment:
      # Shopware Administration Watch Host
      - HOST=0.0.0.0
      # Shopware Administration Watch Port
      - PORT=9997
      # Expose APP_URL to administration watcher
      - APP_URL=http://${DDEV_SITENAME}.ddev.site
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,9998:9998,9997:9997
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,8888:9998,8887:9997
```

3. Step: ddev start

Finally you can watch:
Administration: http://domain.tld.ddev.site:9997
Storefront: http://domain.tld.ddev.site:9998

It's only working without SSL.
