### ISSUE TITLE
Sitemap URLs are potentially missing the first character `s` when using S3 Storage

### ISSUE THREAD

**Issue by jr-timme** [shopware/platform#3312]
### PHP Version

8.2

### Shopware Version

6.5.4.0, 6.5.3.3

### Expected behaviour

The sitemap URLs should be generated so that they work

### Actual behaviour

The sitemap URLs are missing the `s` of `sitemap` inside the URLs, e.g. `https://mydomain.com/itemap/...`

### How to reproduce

1. Install Shopware 6
2. Configure S3 as your Filesystem through a `config/packages/z-shopware.yaml` and set the `root` to `/`
e.g.
```yaml
shopware:
[...]
    filesystem:
        public:
            url: "https://%env(MY_DOMAIN)%/%env(MY_BUCKET)%/"
            type: "amazon-s3"
            visibility: "public"
            config:
                bucket: "%env(MY_BUCKET)%"
                region: "eu-central-1"
                endpoint: "https://%env(MY_ENDPOINT)%"
                use_path_style_endpoint: true
                root: "/"
                credentials:
                    key: "%env(MY_ACCESS_KEY_ID)%"
                    secret: "%env(MY_SECRET_ACCESS_KEY)%"
```

We did set `root` to `/` because that's where the files are stored. If we change `root` to the empty String `''` the URLs work correctly.

This happens because `root` is used as `$prefix`  and so it has a length of 1 which leads to the first character, which is the `s`, being removed through:
- [vendor/shopware/core/Framework/Adapter/Filesystem/Adapter/AwsS3v3Factory.php#L45-L48](https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Adapter/Filesystem/Adapter/AwsS3v3Factory.php#L45-L48)
- [vendor/shopware/core/Content/Sitemap/Service/SitemapLister.php#L27](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Sitemap/Service/SitemapLister.php#L27)
- [vendor/shopware/core/Framework/Adapter/Filesystem/Adapter/DecoratedAsyncS3Adapter.php#L131-L134](https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Adapter/Filesystem/Adapter/DecoratedAsyncS3Adapter.php#L131-L134)
- [vendor/league/flysystem-async-aws-s3/AsyncAwsS3Adapter.php#L281-L303](https://github.com/thephpleague/flysystem-async-aws-s3/blob/3.x/AsyncAwsS3Adapter.php#L281-L303)
- [vendor/league/flysystem-async-aws-s3/AsyncAwsS3Adapter.php#L410-L451](https://github.com/thephpleague/flysystem-async-aws-s3/blob/3.x/AsyncAwsS3Adapter.php#L410-L451)
- [vendor/league/flysystem/src/PathPrefixer.php#L29-L33](https://github.com/thephpleague/flysystem/blob/3.x/src/PathPrefixer.php#L29-L33)

I'm not sure if this is actually a bug or if this might be the intended behaviour.
At the very least I think it should be documented, that `root` should not contain any leading `/`
[docs/blob/master/guides/hosting/infrastructure/filesystem.md?plain=1#L103](https://github.com/shopware/docs/blob/master/guides/hosting/infrastructure/filesystem.md?plain=1#L103)
