### ISSUE TITLE
rate_limiter doesn't work as described in DEV Docu

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#4229]
**EN**   
According to the DEV documentation ([https://developer.shopware.com/docs/guides/hosting/infrastructure/rate-limiter.html?_gl=1*5h7k4n*_ga*MTkyODE0ODE0OS4xNzA2MDc5MTkx*_ga_9JLJ6GGB76*MTcwNzgwNzc2Ny45LjEuMTcwNzgyMjYyMS4wLjAuMA](https://developer.shopware.com/docs/guides/hosting/infrastructure/rate-limiter. html?_gl=1*5h7k4n*_ga*MTkyODE0ODE0OS4xNzA2MDc5MTkx*_ga_9JLJ6GGB76*MTcwNzgwNzc2Ny45LjEuMTcwNzgyMjYyMS4wLjAuMA)) can be accessed via the shopware. yaml or z-shopware.yaml to limit the number of incorrect login attempts and set a time limit. 

If I add the example:

```
// <shop root>/config/packages/shopware.yaml
shopware:
  api:
    rate_limiter:
      login:
        enabled: false
      oauth:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
```
in my z-shopware.yaml, no problems occur. But now I want to use my own defaults for the `login' limiter and change the entry to :
```
// <shop root>/config/packages/shopware.yaml
shopware:
  api:
    rate_limiter:
      login:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
      oauth:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
```
I would now expect that after compiling the frontend and deleting the cache, it would no longer be possible to log in for 10 seconds after three login attempts. However, I actually get a message in the admin about an HTTP 500 error and after a refresh the admin is not accessible (white page). If I remove the setting completely and refresh, everything is fine again. 

To me, this looks like a bug in this function, so please check and correct it. If the documentation is incomplete, please forward it there for correction.

---

**DE**    
Laut DEV Doku ([https://developer.shopware.com/docs/guides/hosting/infrastructure/rate-limiter.html?_gl=1*5h7k4n*_ga*MTkyODE0ODE0OS4xNzA2MDc5MTkx*_ga_9JLJ6GGB76*MTcwNzgwNzc2Ny45LjEuMTcwNzgyMjYyMS4wLjAuMA](https://developer.shopware.com/docs/guides/hosting/infrastructure/rate-limiter.html?_gl=1*5h7k4n*_ga*MTkyODE0ODE0OS4xNzA2MDc5MTkx*_ga_9JLJ6GGB76*MTcwNzgwNzc2Ny45LjEuMTcwNzgyMjYyMS4wLjAuMA)) kann über die shopware.yaml bzw. z-shopware.yaml die Anzahl der fehlerhaften Anmeldeversuche beschränkt und mit einer zeitlichen Sperre belegt werden. 

Trage ich das Beispiel:
```
// <shop root>/config/packages/shopware.yaml
shopware:
  api:
    rate_limiter:
      login:
        enabled: false
      oauth:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
```
in meiner z-shopware.yaml ein, treten keine Schwierigkeiten auf. Nun möchte ich aber für den Limiter `login' eigene Vorgaben verwenden und ändere den Eintrag auf:
```
// <shop root>/config/packages/shopware.yaml
shopware:
  api:
    rate_limiter:
      login:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
      oauth:
        enabled: true
        policy: 'time_backoff'
        reset: '24 hours'
        limits:
          - limit: 3
            interval: '10 seconds'
          - limit: 5
            interval: '60 seconds'
```
Ich würde nun erwarten, dass nach einer Kompilierung des Frontends und Löschen des Caches nach drei Anmeldeversuchen 10 Sekunden lang keine Anmeldung mehr möglich ist. Tatsächlich erhalte ich im Admin aber einen Hinweis auf einen HTTP 500 Fehler und nach einem Refresh ist der Admin nicht erreichbar (weiße Seite). Entferne ich die Einstellung komplett und refeshe, ist alles wieder in Ordnung. 

Für mich sieht das nach einem Bug in dieser Funktion aus, daher bitte prüfen und korrigieren. Falls die Dokumentation unvollständig ist, bitte zur Korrektur dort weiterleiten.
