### ISSUE TITLE
Scroll-Up Button gets re-positioned in mobile view after CMS-Extensions are activated

### ISSUE THREAD

**Issue by JURshopware** [shopware/platform#4675]
*PHP Version:* 8.2   | *Shopware Version:* 6.6.6.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Expected behaviour:_*

By default, the scroll up button is shown in the bottom right corner. 

*_Actual behaviour:_*

As soon as the CMS-Extensions are enabled, these attributes are added(!) to the all.css, leading to the scroll up button being shown in the bottom left corner in the mobile view. 

```css
.scroll-up-button {
    display: block;
    left: 1.5rem;
    right: auto
}
 .scroll-up-button {
        left: auto;
        right: 1.5rem
    }
```

These overwrite the following attributes:

```css
.scroll-up-button {
    bottom: 1.5rem;
    cursor: pointer;
    opacity: 0;
    position: fixed;
    right: 1.5rem;
    transform: scale(0);
    transition: 0.45s cubic-bezier(0.3, 0, 0.15, 1);
    visibility: hidden;
    z-index: 700
}
.scroll-up-button.is-visible {
    opacity: 1;
    transform: scale(1);
    visibility: visible
}
```

*_How to reproduce:_*

1. Open storefront (with inactive CMS-Extensions)
2. Switch to mobile views --> scroll up button is shown in the bottom right corner
3. Enable CMS Extensions
4. Refresh Storefront page --> in mobile view, the scroll up button is now shown in the bottom left corner
