### ISSUE TITLE
[Github] Fix locale in contextcontroller

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#4913]
### 1. Why is this change necessary?

Currently when using a custom `config/routes/routes.yaml` the redirect after a language switch doesn't work correctly because the '_locale' that is submitted in the form is the locale of the current language and not the locale of the new language.

### 2. What does this change do, exactly?

Adds a hidden input field

`<input type="hidden" name="languageCode_{{ language.id }}" value="{{ language.translationCode.code }}">`

that is used to grab the language code from the new language and adds it as a redirect parameter

### 3. Describe each step to reproduce the issue or behaviour.

Add custom routes.yaml:

```
frontend.wishlist.page:
    path:
        en-GB: '/wishlist'
        de-DE: '/merkliste'
    controller: 'Shopware\Storefront\Controller\WishlistController::index'
    methods: ['GET']
    defaults:
        _noStore: true
        _routeScope: ['storefront']
    options:
        seo: false
frontend.account.home.page:
    path:
        en-GB: '/account'
        de-DE: '/konto'
    controller: 'Shopware\Storefront\Controller\AccountProfileController::index'
    methods: ['GET']
    defaults:
        _noStore: true
        _loginRequired: true
        _routeScope: ['storefront']
```

Go to wishlist or account home page and switch language. Localized path isn't respected because of this piece of code that adds the current locale:

```
{% for key, value in app.request.attributes.get('_route_params') %}
        <input name="redirectParameters[{{ key }}]" type="hidden" value="{{ value }}">
{% endfor %}
```

For example, when switching on /account from English to German the en-GB locale is in the route_params (current locale): 

`<input name="redirectParameters[_locale]" type="hidden" value="en-GB">`

This results in a redirect to /de/account instead of /de/konto 

Before change (with routes.yaml):
https://github.com/shopware/shopware/assets/26538915/0ab41131-4987-44a1-916a-76ef4059149d

After change (with routes.yaml):
https://github.com/shopware/shopware/assets/26538915/9c522f6a-1806-40a9-b16d-56d40f622c4a

### 4. Please link to the relevant issues (if any).
N/A

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/3782
