### ISSUE TITLE
Storefront watcher not working correctly in shopware 6.6.6.1

### ISSUE THREAD

**Issue by yanneckb** [shopware/platform#5005]
*PHP Version:* 8.2   | *Shopware Version:* 6.6.6.1  | *Affected area / extension:* Platform(Default) 

 ----

*_Expected behaviour:_*

Hey guys,
I have a new shopware 6.6.6.1 project runnning with ddev 1.23.1 (php v8.2, mysql v8, node v20.13.1) but the storefront watcher is making some problems... the watcher should work correctly with all assets displayed and reacting to changes, when i start it in the ddev ssh via `bin/watch-storefront.sh`

*_Actual behaviour:_*

First i got a deprecated warning with puppeteer and a chromium install error. I fixed it by adding "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" to the config.watcher.yaml:

```
### ./.ddev/config.watcher.yaml ###

web_extra_exposed_ports:
  - name: storefront-watcher
    container_port: 9998
    http_port: 9998
    https_port: 9998 ## also tried 9999
  - name: admin-watcher
    container_port: 8888
    http_port: 8888
    https_port: 8889

web_environment:
  - HOST=0.0.0.0
  - PORT=9998
  - APP_URL=${DDEV_PRIMARY_URL}
  - ESLINT_DISABLE=true
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
``` 

The watcher starts now, but i get this error:
```
Unable to open browser! Details:
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'https://richartz-shop.ddev.site:9998/' ]
}
```

but this is not my main problem, the REAL problem is, that the watcher is running on https://my-shop.ddev.site:9998/, but all the images are loaded via http://my-shop.ddev.site:9998/. When i go to https://my-shop.ddev.site/ all images are loaded via https again. Only the watcher is making problems...
Also tried adding this to public/.htaccess:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
```

Does anybody have an idea? When i start the project with devenv, everything is working fine... only with ddev i have problems

Greetings!
Yanneck

*_How to reproduce:_*

Set up new shopware 6.6 project with ddev and add storefront watcher configuration

**Comment by yanneckb** [comment]
EDIT: I also tried this configuration in the .ddev/config.watcher.yaml. With this the page is not working at all:

```
# .ddev/docker-compose.watcher.yaml
services:
    web:
        expose:
            - 9997
            - 9998
            - 9999
        environment:
            - ESLINT_DISABLE=true
            - HOST=0.0.0.0
            - PORT=9997
            - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,9998:9998,9997:9997
            - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,8888:9998,8887:9997
```
