### ISSUE TITLE
[Extension: Commercial] Cart lost at logout with Redis persister

### ISSUE THREAD

**Issue by raffaelecarelle** [shopware/platform#5170]
*PHP Version:* 8.3   | *Shopware Version:* 6.6.6.0  | *Affected area / extension:* Extension:Commercial 

 ----

*_Expected behaviour:_*

When user logs out and then log in again, he has his cart correctly restored with all lineitems previously added in.

PS. Settings > Log-in & sign-up > Clear and delete cart on log-out is set to FALSE

*_Actual behaviour:_*

After logout and than log in, the user lost his cart.

*_How to reproduce:_*

0. activate cart redis storage
1. Install and activated Commercial plugin.
2. Install demo data
3. register
4. login
5. add product in the cart
6. logout
7. login again
8. the cart is lost

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-39139**



[created from NEXT-39139, comment 505208]

**Comment by florianliebig** [comment]
Can not reproduce without Commercial plugin with this config in latest trunk with php 8.2:

```
shopware:
    redis:
        connections:
            persistent:
                dsn: 'redis://127.0.0.1:6379/1?persistent=1'
    cart:
        storage:
            type: 'redis'
            config:
                connection: 'persistent'

framework:
  session:
    handler_id: "redis://127.0.0.1:6379"
```

So most likely really something with the commercial plugin or some other setting
