### ISSUE TITLE
[Shopware 6.6.8.0] start-hot-reload fix destroys ddev watcher

### ISSUE THREAD

**Issue by yanneckb** [shopware/platform#5495]
*PHP Version:* 8.3   | *Shopware Version:* 6.6.8.2  | *Affected area / extension:* Platform(Default) 

 ----

*_Expected behaviour:_*

Hello guys,
We updated to the new version shopware 6.6.8.2 and now our watcher wont work anymore because of the start-hot-reload changes in 6.6.8.0/6.6.8.1...
We use a watcher configuration for ddev and when we started via `bin/watch-storefront.sh`

*_Actual behaviour:_*

Now we get the error, that the env vars `STOREFRONT_HTTPS_KEY_FILE`and `STOREFRONT_HTTPS_CERTIFICATE_FILE` are missing. Ive added them with an empty string as a value and the error in the console is gone.
But the main thing is that the compiled css and js files are not being loaded because they are requested over http instead of https...

Could be these changes. Maybe I just have to tweak the watcher configuration

Changes: https://github.com/shopware/shopware/issues/2802#issuecomment-2440827014

Error Message (for every compiiled js and css):
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.
my-shop.ddev.site/:1 Mixed Content: The page at 'https://my-shop.ddev.site:9998/' was loaded over HTTPS, but requested an insecure script 'http://my-shop.ddev.site:9999/storefront/css.js'. This request has been blocked; the content must be served over HTTPS.
my-shop.ddev.site/:1
```

*_How to reproduce:_*

Start the watcher with "bin/watch-storefront.sh" in a Shopware >=6.6.8.0 Setup with ddev and this ddev configuration:

```
#####################
### .ddev/config.yaml
#####################
name: my-shop
type: shopware6
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
performance_mode: none
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false

#############################
### .ddev/config.watcher.yaml
#############################
web_environment:
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  - ENV_FILE=${DDEV_COMPOSER_ROOT}/.env.local

additional_hostnames: ["my-shop.ddev.site", "*.ddev.site.ddev.site", "my-shop.ddev.site.ddev.site"]

#####################################
### .ddev/docker-compose-watcher.yaml
#####################################
services:
  web:
    expose:
      - 9997
      - 9998
      - 9999
    environment:
      - ESLINT_DISABLE=true
      - HOST=0.0.0.0
      - PORT=9997
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,8899:9999,8888:9998,8887:9997
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,9999:9999,9998:9998,9997:9997
```

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-39608**



[created from NEXT-39608, comment 512778]

**Comment by BrocksiNet** [comment]
Hi, thx for reporting. We already worked on that problem.

Can you try with this changed file:

***start-hot-reload.js*** (from 2024-11-22)
```
/* eslint no-console: 0 */
const { createProxyMiddleware } = require('http-proxy-middleware');
const nodeServerHttp = require('node:http');
const nodeServerHttps = require('node:https');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const createLiveReloadServer = require('./live-reload-server/index');

const proxyPort = Number(process.env.STOREFRONT_PROXY_PORT) || 9998;
const assetPort = Number(process.env.STOREFRONT_ASSETS_PORT) || 9999;

const projectRootPath = process.env.PROJECT_ROOT
    ? path.resolve(process.env.PROJECT_ROOT)
    : path.resolve('../../../../..');
const themeFilesConfigPath = path.resolve(projectRootPath, 'var/theme-files.json');
const themeFiles = require(themeFilesConfigPath);
const domainUrl = new URL(themeFiles.domainUrl);
const themeUrl = new URL(`${domainUrl.protocol}//${domainUrl.host}`);

const appUrlEnv = themeUrl ? themeUrl : new URL(process.env.APP_URL);
const keyPath = process.env.STOREFRONT_HTTPS_KEY_FILE || `${process.env.CAROOT}/${themeUrl.hostname}-key.pem`;
const certPath = process.env.STOREFRONT_HTTPS_CERTIFICATE_FILE || `${process.env.CAROOT}/${themeUrl.hostname}.pem`;
const skipSslCerts = process.env.STOREFRONT_SKIP_SSL_CERT === 'true';
const sslFilesFound = (fs.existsSync(keyPath) && fs.existsSync(certPath));

const proxyProtocol = (appUrlEnv.protocol === 'https:' && sslFilesFound || skipSslCerts) ? 'https:' : 'http:';
const proxyUrlEnv = new URL(process.env.PROXY_URL || `${proxyProtocol}//${appUrlEnv.hostname}:${proxyPort}`);

const proxyOptions = {
    appPort: Number(appUrlEnv.port) || undefined,
    host: appUrlEnv.host,
    proxyHost: proxyUrlEnv.host,
    proxyPort: proxyPort,
    secure: appUrlEnv.protocol === 'https:' && sslFilesFound && !skipSslCerts,
    selfHandleResponse: true,
    target: appUrlEnv.origin,
    autoRewrite: true,
    followRedirects: false, // if you activate followRedirects, cookies will be lost !!!
    changeOrigin: true,
    headers: {
        host: appUrlEnv.host,
        'hot-reload-mode': 'true',
        'accept-encoding': 'identity',
    },
    cookieDomainRewrite: {
        '*': '',
    },
    cookiePathRewrite: {
        '*': '',
    },
    on: {
        proxyReq: (proxyReq, req) => {
            // Hot reload updates
            if (req.url.indexOf('/sockjs-node/') === 0 || req.url.indexOf('hot-update.json') !== -1 || req.url.indexOf('hot-update.js') !== -1) {
                proxyReq.host = '127.0.0.1';
                proxyReq.port = assetPort;
            }
        },
        proxyRes: (proxyRes, req, res) => {
            let body = [];
            // Set the cookie from the proxy response to the next proxy request
            if (proxyRes.headers['set-cookie']) {
                res.setHeader('set-cookie', proxyRes.headers['set-cookie']);
            }
            proxyRes.on('data', (chunk) => {
                body.push(chunk);
            });
            proxyRes.on('end', () => {
                // this will fix the display of the SVGs in chrome browser
                if (req.url.indexOf('.svg') !== -1) {
                    res.setHeader('Content-Type', 'image/svg+xml');
                }
                // here we replace the redirect url and add the offcanvas=1 parameter to the url
                if (req.url === '/checkout/line-item/add') {
                    body = Buffer.concat(body).toString();
                    body = body.replace(new RegExp('content="0;url=\'/checkout/offcanvas\'"', 'g'), 'content="0;url=\'?offcanvas=1\'"')
                    res.end(body);
                    return;
                }
                // we only replace things when the request is a document
                if (req.headers['sec-fetch-dest'] === 'document') {
                    body = Buffer.concat(body).toString();
                    // if we have the offcanvas=1 parameter in the url, we will attach a script to open the offcanvas cart
                    if (req.url.indexOf('offcanvas=1') !== -1) {
                        body = body.concat(openOffCanvasScript());
                    }
                    body = body
                        // replace the webpack hot proxy with the url of the live reload server
                        .replace(new RegExp('/_webpack_hot_proxy_/', 'g'), `${proxyUrlEnv.protocol}//${proxyUrlEnv.hostname}:${assetPort}/`)
                        // replace the domain without port or without port with the proxy url
                        .replace(new RegExp(`${appUrlEnv.origin}/`, 'g'), `${proxyUrlEnv.origin}/`)
                        // replace the media url back to use the default storefront url
                        .replace(new RegExp(`${proxyUrlEnv.origin}/media/`, 'g'), `${appUrlEnv.origin}/media/`)
                        // replace the thumbnail url back to use the default storefront url
                        .replace(new RegExp(`${proxyUrlEnv.origin}/thumbnail/`, 'g'), `${appUrlEnv.origin}/thumbnail/`)
                        // Replace Symfony Profiler URL to relative url @see: https://regex101.com/r/HMQd2n/2
                        .replace(/http[s]?\\u003A\\\/\\\/[\w.]*(:\d*|\\u003A\d*)?\\\/_wdt/gm, '/_wdt')
                        .replace(/new\s*URL\(url\);\s*url\.searchParams\.set\('XDEBUG_IGNORE'/gm, 'new URL(window.location.protocol+\'//\'+window.location.host+url);                url.searchParams.set(\'XDEBUG_IGNORE\'');
                    res.end(body);
                    return;
                }
                // when we use the .toString method on Buffer, the body will be converted to a string
                // this can lead to problems with binary files like fonts (e.g. woff2)
                res.end(Buffer.concat(body));
            });
        },
        error: (err, req, res) => {
            console.error(err);

            if (err.code === 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY') {
                console.error('Make sure that node.js trusts the provided certificate. Set NODE_EXTRA_CA_CERTS for this.');
                console.error(`Try to start again with NODE_EXTRA_CA_CERTS="${certPath}" set.`);
                process.exit(1);
            }

            if (err.code === 'SSL_ERROR_NO_CYPHER_OVERLAP') {
                console.error('Try to start watcher again with specific path to https (key and crt) files like this:');
                console.error('STOREFRONT_HTTPS_KEY_FILE=/var/www/html/.../certs/shopware.key STOREFRONT_HTTPS_CERTIFICATE_FILE=/var/www/html/../certs/shopware.crt composer run watch:storefront');
                process.exit(1);
            }

            if (err.code === 'ENOTFOUND') {
                console.error('The domain could not be resolved. Make sure that the domain is correct in DEVENV/DDEV.');
                console.error('And if this is a custom domain, make sure that the domain is set in your /etc/hosts file.');
                process.exit(1);
            }

            res.writeHead(500, {
                'Content-Type': 'text/plain',
            });
            res.end('Something went wrong. Check the console for more information.');
        },
    },
};

if (appUrlEnv.protocol === 'https:' && !sslFilesFound) {
    console.error('Could not find the key and certificate files.');
    console.error('Make sure that the environment variables STOREFRONT_HTTPS_KEY_FILE and STOREFRONT_HTTPS_CERTIFICATE_FILE are set correctly.');
    console.error('If you use a TLS proxy (like in DDEV Shopware 6 setup), you can ignore this message.');
}

const sslOptions = proxyUrlEnv.protocol === 'https:' && skipSslCerts === false ? {
    key: fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
} : {};

const proxyServerOptions = Object.assign(proxyOptions, { ssl: sslOptions });
const proxy = createProxyMiddleware(proxyServerOptions);
const server = createLiveReloadServer(sslOptions).catch((e) => {
    console.error(e);
    console.error('Could not start the live server with the provided certificate files, falling back to http server.');
    return createLiveReloadServer({});
});
server.then(() => {
    console.log('############');
    console.log(`Default TWIG Storefront: ${appUrlEnv.origin}`);
    console.log(`Proxy server hot reload: ${proxyUrlEnv.origin}`);
    console.log('############');

    if (proxyUrlEnv.protocol === 'https:' && skipSslCerts === false) {
        try {
            nodeServerHttps.createServer(sslOptions, proxy).listen(proxyPort);
            console.log('Proxy uses the https schema, with ssl certificate files.');
        } catch (e) {
            console.error(e);
            console.error('Could not start the proxy server with the provided certificate files, falling back to http server.');
            proxyUrlEnv.protocol = 'http:';
        }
    }

    if (proxyUrlEnv.protocol === 'http:' || skipSslCerts === true) {
        console.log(`Proxy uses the http schema${skipSslCerts ? ' (SSL certificates are skipped).' : '.'}`);
        nodeServerHttp.createServer(proxy).listen(proxyPort);
    }

    console.log('############');
    console.log('\n');

    openBrowserWithUrl(`${proxyUrlEnv.origin}`);
});

function openOffCanvasScript() {
    return '<script>document.addEventListener("DOMContentLoaded", () => { setTimeout(() => { if (!document.querySelector(".header-cart-total").textContent.includes("0.00")) { document.querySelector(".header-cart").click(); } }, 500); });</script>';
}

function openBrowserWithUrl(url) {
    const start = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
    const child = spawn(start, [url], { stdio: 'ignore', detached: true });
    child.on('error', error => console.log('Unable to open browser! Details:', error));
}

```

And make sure your watch-storefront script looks like [this](https://github.com/shopware/recipes/commit/6ac022bc4bb7728313f0a1a061d6891b33b7d118).

After that, you can start it with that command in DDEV ssh/shell:
`STOREFRONT_SKIP_SSL_CERT=true PROXY_URL=https://shopware-ddev-new.ddev.site:9998 bin/watch-storefront.sh `

And yes, change the `PROXY_URL` to your current URL.

Please give me feedback on whether this will work. MR is in preparation.

**Comment by yanneckb** [comment]
Hi @BrocksiNet,
tried these changes with my ddev configuration but it doesn't work. Then I changed my configuration to this https://notebook.vanwittlaer.de/ddev-for-shopware/storefront-and-admin-watchers-with-ddev
The watcher works but the assets are not loaded correctly (not all but some images and all fonts). 

Also the watcher asks which theme has to be compiled every time
```zsh
Please select a theme:
  [0] Shopware default theme
  [1] MyShopTheme
 > 1
Please select a domain url:
  [0] http://my-shop.ddev.site
  [1] https://my-shop.ddev.site
 > 1
```

**Comment by BrocksiNet** [comment]
Parts of the `.ddev/config.yaml` we used for testing:
```
web_environment:
    - APP_DEBUG=1
    - APP_ENV=dev
    - APP_URL=${DDEV_PRIMARY_URL}
    - DATABASE_URL=mysql://db:db@db:3306/db
    - MAILER_DSN=smtp://localhost:1025?encryption=&auth_mode=
    - HOST=0.0.0.0
    - PORT=9997
    - PROXY_URL=${DDEV_PRIMARY_URL}:9998
    - STOREFRONT_SKIP_SSL_CERT=true
web_extra_exposed_ports:
    - name: admin-proxy
      container_port: 9997
      http_port: 8887
      https_port: 9997
    - name: storefront-proxy
      container_port: 9998
      http_port: 8888
      https_port: 9998
    - name: storefront-assets
      container_port: 9999
      http_port: 8889
      https_port: 9999
```

The selection of theme and domain pops up when you have more than one theme and more than one domain (new Feature).

What in detail is the problem with images and fonts? Benny vanWittlaer also validated the change with DDEV.
