### ISSUE TITLE
Numbers are ignored in the search

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#5576]
In a store with Advanced Search, the products are always given the same ranking score regardless of the number after the product name.  
For example:
The following products exist:
Main article 1
Main article 2
Main article 3

You now search for main article 2.

Result:
All three products receive the same ranking score and the number after the product name is ignored.

Expected result:
Main article 2 receives the highest ranking score, as this article was explicitly searched for.

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **NEXT-39706**



[created from NEXT-39706, comment 514229]

**Comment by Fewiel** [comment]
Same with the default search. 

Example:  
AVC-A1H  

You search for AVC - You find the Product  
You search for A1H - No results

**Comment by tamvt** [comment]
@Fewiel it could be fixed by adjusting the analysis filter configuration in elasticsearch.yaml

```yaml
elasticsearch:
    analysis:
        filter:
            sw_ngram_filter:
                type: ngram
                min_gram: 3 // it was 4 by default
                max_gram: 4 // it was 5 by default
```

After this change and reindexing Elasticsearch, the search for “A1H” works. 

Could you double check if it works?
