### ISSUE TITLE
[Github] fix: Added `default` node structure for the `system_config` node

### ISSUE THREAD

**Issue by shopwareBot** [shopware/platform#5597]
### 1. Why is this change necessary?
https://issues.shopware.com/issues/NEXT-35831 issue introduced possibility to define system config through yaml `shopware.system_config` node. However - current implementation does not allow to merge system_config node settings from multiple, environment dependent yaml files.

### 2. What does this change do, exactly?
Allows to merge `shopware.system_config` yaml nodes from multiple yaml config files.

### 3. Describe each step to reproduce the issue or behaviour.
Create new yaml file for system config e.g: `config/packages/system_config.yaml` with content like:
```
shopware:
    system_config:
        default:
            core.mailerSettings.host: 'some-host'
            core.mailerSettings.port: 465
            core.mailerSettings.emailAgent: 'smtp'
```
Create another yaml file specific for `dev` environment e.g `config/packages/dev/system_config.yaml` with content:
```
shopware:
    system_config:
        default:
            core.mailerSetting.disableDelivery: true
```

Notice now that `vendor/shopware/core/System/SystemConfig/SymfonySystemConfigService.php` receives only configuration from `config/packages/dev/system_config.yaml`, all configurations from base file are compeletelly ommited. 

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/webwirkung-michal-d/shopware/blob/fix/system-config-default-node-structure/changelog/_unreleased/2024-07-17-defined-system-config-default-node-structure.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/3808
