### ISSUE TITLE
watch-storefront does not render assets

### ISSUE THREAD

**Issue by Peeet93** [shopware/platform#5702]
*PHP Version:* 8.2   | *Shopware Version:* 6.6.8.2  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

I try to run the bin/watch-storefront.sh script. Everything is working as expected until i open my frontend.

I added this scss:
```scss
@font-face {
  font-display : swap;
  font-family  : "SofiaPro";
  font-weight  : 700;
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_0_0.eot");
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_0_0.eot?#iefix") format("embedded-opentype"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_0_0.woff2") format("woff2"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_0_0.woff") format("woff"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_0_0.ttf") format("truetype");
}

@font-face {
  font-display : swap;
  font-family  : "SofiaPro";
  font-weight  : 300;
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_1_0.eot");
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_1_0.eot?#iefix") format("embedded-opentype"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_1_0.woff2") format("woff2"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_1_0.woff") format("woff"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_1_0.ttf") format("truetype");
}

@font-face {
  font-display : swap;
  font-family  : "SofiaPro";
  font-weight  : 400;
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/383747_2_0.eot");
  src          : url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_2_0.eot?#iefix") format("embedded-opentype"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_2_0.woff2") format("woff2"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_2_0.woff") format("woff"), url("#{$sw-asset-public-url}/bundles/dockwaresampleplugin/fonts/383747_2_0.ttf") format("truetype");
}


body {
  font-family : "SofiaPro";
  background  : yellow;
}
```

In my network tab, the fonts are loaded but they are not rendered.

*_Expected behaviour:_*

The font and every other assets are loaded

*_How to reproduce:_*

Run this docker compose file:

```
services:
  app:
    image: dockware/dev:6.6.8.2
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    ports:
      - "80:80"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.2

networks:
  web:
    external: false

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local
``` 

add the scss and fonts to the DockwareSamplePlugin.
Run the bin/watch-storefront.sh script.
open localhost:9998
