### ISSUE TITLE
Redis configuration for number_range causes exception

### ISSUE THREAD

**Issue by h1k3r** [shopware/platform#8152]
### PHP Version

8.2.27

### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Configuring number_range redis storage causes 500 error:
```yaml
shopware:
    redis:
        connections:
            ephemeral:
                dsn: 'redis://localhost:6379/1'
            persistent:
                dsn: 'redis://localhost:6379/2'
    number_range:
        increment_storage: "redis"
        config:
            connection: 'persistent'
```

Exception message:
`Redis::__construct(): Argument #1 ($options) must be of type ?array, string given`

### Expected behaviour

To work as documented: https://developer.shopware.com/docs/guides/hosting/performance/number-ranges.html

### How to reproduce

Add configuration above to the config/packages/shopware.yaml, reload the page.
