### ISSUE TITLE
HTML-Sanitizer - "style" attribute for "img" tag is not sanitized although it is NOT whitelisted

### ISSUE THREAD

**Issue by JURshopware** [shopware/platform#8267]
### Shopware Version

6.6.10.2

### Affected area / extension

Platform(Default)

### Actual behaviour

/config/packages/shopware.yaml looks like the following:

```yaml
shopware:
    html_sanitizer:
        sets:
            -   name: basic
                tags: [ "img" ]
                attributes: [ "src", "alt" ]
                options:
                    - key: HTML.Trusted
                      value: true
                    - key: CSS.Trusted
                      value: true
```

It is still possible to use the "style" attribute in "img" tags and it will not be sanitized. 

### Expected behaviour

Excluding the "style" attribute should lead to it being sanitized if it is used within an HTML editor

### How to reproduce

- Add the following config to your shopware.yaml (see above)
- Clear cache afterwards
- Open product and switch to the HTML Editor view in field "description" for example
- Insert "img" tag with "style" attribute e.g. `<img src="smiley.gif" alt="Smiley face" width="42" height="42" style="border:4px solid #1b6b6f;padding:15px;" />`

Result: `style="border:4px solid #1b6b6f;padding:15px;"` still remains after saving and is not being sanitized.
