### ISSUE TITLE
Message routing overwrite broken for interfaces and abstract classes

### ISSUE THREAD

**Issue by sjerdo** [shopware/platform#8434]
### Shopware Version

v6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

Project has a message routing overwrite configured for all EntityIndexMessage objects:

```yaml
shopware:
  messenger:
    routing_overwrite:
      'Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexingMessage': transport_entity_index
```

In Shopware v6.6.10.3 the message is routed to the default transport _async_

The RoutingOverwriteMiddleware does not properly check for interfaces or abstract classes:
```php
        foreach ($overwrites as $class => $transports) {
            if ($message instanceof $class) {
                return $transports;
            }
        }
```

Since the `$message` object is the Envelope class, this only works for overwrites where the class is set to  `Symfony\Component\Messenger\Envelope`

This bug was fixed in NEXT-39749 https://github.com/shopware/shopware/commit/ec0117751339750e6622e0e08288a9fffb0c4d29 but reintroduced in the messenger refactor in NEXT-39755 https://github.com/shopware/shopware/commit/a1db8b09e3c4db1834429cac6f7530cb1c03e379

### Expected behaviour

In Shopware v6.6.8.2 this works as expected and routes the entity index messages to transport _transport_entity_index_

### How to reproduce

Add a custom transport `transport_entity_index`

Configure a message routing overwrite for the entity index messages:

```yaml
shopware:
  messenger:
    routing_overwrite:
      'Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexingMessage': transport_entity_index
```
