### ISSUE TITLE
Copy batch ignores visibility configuration for S3

### ISSUE THREAD

**Issue by jonaaix** [shopware/platform#8770]
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

With the following code in `src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatch.php`:
```php
$adapter = self::getAdapter($filesystem);
if ($adapter instanceof WriteBatchInterface) {
    $adapter->writeBatch(...$files);
    return;
}
``` 

...and when the filesystem is configured to use S3 (tested with DigitalOcean Spaces) like this:

```yaml
# config/packages/shopware.yaml
shopware:
  filesystem:
    asset:
        type: "amazon-s3"
        visibility: "public"
        url: "%env(string:S3_URL)%/%env(string:S3_ROOT_DIR_PUBLIC)%"
        config:
            bucket: "%env(string:S3_BUCKET)%"
            region: "%env(string:S3_REGION)%"
            endpoint: "%env(string:S3_ENDPOINT)%"
            root: "%env(string:S3_ROOT_DIR_PUBLIC)%"
            credentials:
                key: "%env(string:S3_KEY)%"
                secret: "%env(string:S3_SECRET)%"
``` 

...then **visibility is ignored**, and all copied files are uploaded as `private`, even when they should be public.

Testable by republishing the assets `bin/console assets:install --force`.

**Removing the `writeBatch` code block above resolves the issue.**

### Expected behaviour

Copied assets should respect the configured visibility settings (e.g. "public").

### How to reproduce

1. Configure filesystem to use S3/Spaces with visibility: "public" in config/packages/shopware.yaml
2. Trigger an asset copy process `bin/console assets:install --force`
3. Check visibility of the files in the S3 bucket or try to load the admin dashboard
4. The dashboard will not load since asset files are private, network requests will get 403
